### PR TITLE
Add discount_amount and discounted_price

### PR DESCRIPTION
**Pull request by bradleypriest**

### CODE REVIEW

**Comment by pmdeazeta** [comment]
Should we update the CreateOrderLineItem service in the main app to auto-populate `discount` when `discount_amount` is passed on the API? We might have some issues on accounting if only discount amount is present

**Comment by jasonheecs** [comment]
Or when both `discount_amount` and `discount` is present on the API request :trollface:

**Comment by bradleypriest** [comment]
@pmdeazeta what kind of issues? Surely we should update the accounting integrations to support both?

**Comment by bradleypriest** [comment]
> Or when both `discount_amount` and `discount` is present on the API request :trollface:

Validation error right?

**Comment by jasonheecs** [comment]
> @pmdeazeta what kind of issues? Surely we should update the accounting integrations to support both?

Accounting integrations rely on the `discount` attribute; we sync the discount rate over to the accounting integration instead of an absolute value. When we import an order from Shopify, we populate the `discount_amount` from the API response and work out the `discount` via this logic:

https://github.com/tradegecko/tradegecko/blob/develop/app/integrations/shopify/services/line_item_discount_service.rb#L52-L59


Question is if we:
a) Receive an API `create` request for `OrderLineItem` with `discount_amount` but without `discount`. We probably need to automatically work out the right `discount` for the `discount_amount` and vice versa.

b) Receive an API `create` request for `OrderLineItem` with `discount_amount` and `discount`. We could throw a validation error if we receive an API request with both attributes, or make it more graceful by only throwing the validation error if both values do not match up.

**Comment by bradleypriest** [comment]
> > @pmdeazeta what kind of issues? Surely we should update the accounting integrations to support both?
> 
> Accounting integrations rely on the `discount` attribute; we sync the discount rate over to the accounting integration instead of an absolute value. When we import an order from Shopify (for an account with the toggle / multi-currency orders), we populate the `discount_amount` from the API response and work out the `discount` via this logic:
> 
> https://github.com/tradegecko/tradegecko/blob/develop/app/integrations/shopify/services/line_item_discount_service.rb#L52-L59
> 
> Question is if we:
> a) Receive an API `create` request for `OrderLineItem` with `discount_amount` but without `discount`. We probably need to automatically work out the right `discount` for the `discount_amount` and vice versa.
> 
> b) Receive an API `create` request for `OrderLineItem` with `discount_amount` and `discount`. We could throw a validation error if we receive an API request with both attributes, or make it more graceful by only throwing the validation error if both values do not match up.

If that's the case, how did the Shipstation issue happen? The discount column wasn't filled in?

**Comment by jasonheecs** [comment]
Not too sure which Shipstation issue is referenced here, but could it have been due to this bug?
https://github.com/tradegecko/tradegecko/pull/17072

**Comment by bradleypriest** [comment]
There was a JIRA issue assigned to you this morning, but yeah that's probably it.
However the updated version is actually more correct than converting amount to percentage and back again, anywhere we can update to do the same (i.e. Accounting integrations etc), we should make the effort

**Pull request merged**
