### PR TITLE
Add payment method record type

### PR DESCRIPTION
**Pull request by wassimk**

### CODE REVIEW

**Comment by lcpriest** [comment]
I believe this is still private! I love that you managed to find it though.

**Comment by wassimk** [comment]
Ha! I don't mean to poke the bear :). I saw it in the customer interface yesterday. I had been using payment_term to kind of hack this in so it was nice to see.

**Comment by lcpriest** [comment]
That was the plan! I think we will wait until we add payments in general to the gem.

**Comment by wassimk** [comment]
Sounds great. I'll actually be working on creating payments tomorrow. I'll do another PR if I do any of it in the gem.

**Comment by lcpriest** [comment]
Are you writing the code yourself, or running thor generate model?

**Comment by wassimk** [comment]
I see the Thor generator in there but haven't used it yet. I just copied and modified payment_term to payment_method today. After I get payments working right in the app we are making I'll try out the Thor generator to create payments for posting back into TradeGecko.

**Comment by lcpriest** [comment]
It even writes the specs for you ;) I was going to modify it to be similar to https://github.com/tradegecko/smaug/blob/master/generate.thor.

That one will actually poll the endpoint and use the JSON to build most of the documentation.

**Comment by wassimk** [comment]
Polling the endpoint is pretty slick.

**Pull request closed without merging**
