### PR TITLE
Add weight unit and value, set weight to read-only

### PR DESCRIPTION
**Pull request by wassimk**
What are your thoughts on tests? I have VCR updating with data from my own TradeGecko. Should I generalize the data and submitted my own updated VCR file? As of now these fields are not tested so they should still pass.

### CODE REVIEW

**Comment by lcpriest** [comment]
This is actually an unstable API, in the interim we are using `weight_value` and `weight_unit` in place of `weight`, but ultimately we want to use `weight` and `weight_unit`.

**Comment by wassimk** [comment]
Hey @lcpriest, any thoughts on what to do temporarily? Just remove read-only? Also, is the weight always going to include the unit or eventually be a BigDecimal? I just want to get them exposed in the GEM so I can use them easier.

``` ruby
      "weight": "487.0g",
      "weight_unit": "g",
      "weight_value": "487.0",
```

**Comment by lcpriest** [comment]
The weight will eventually be BigDecimal. I think we already support using weight (as a decimal) and weight unit. 

I do not want to put weight_value into the gem though.

Thoughts @pmdeazeta? Is it safe to be using weight and weight unit exclusively?

**Comment by lcpriest** [comment]
This is included in https://github.com/tradegecko/gecko/pull/54

**Pull request closed without merging**
